src/helpers/__init__.py
from flask import redirect, session, url_for
from functools import wraps

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'email' not in session:
            return redirect(url_for('public.index'))
        return f(*args, **kwargs)
    return decorated_function

def esta_logueado():
    return 'email' in session

src/modules/private/__init__.py
from flask import Blueprint
import os

# Se declara el blueprint para la vista pública
privado = Blueprint(
    "private",
    __name__,
    url_prefix="/",
    template_folder="templates",
)

# Se manda a llamar al archivo de los endpoints para la vista pública
from . import routes

src/modules/private/routes.py
from flask import render_template
from . import privado
import os


@privado.route("/citas")
def citas():
    return render_template("private/crud.html")

src/templates/error404.html
{% extends "layout.html" %}

{% block content %}
<div class="grid h-[86vh] px-4 bg-white place-content-center dark:bg-gray-900">
  <div class="text-center">
    <h1 class="font-black text-gray-200 text-9xl dark:text-gray-700">404</h1>
    <p
      class="text-2xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
      ¡Oh-no!
    </p>
    <p class="mt-4 text-gray-500 dark:text-gray-400">
      La página que intentas acceder no está disponible
    </p>
    <a href="{{ url_for('public.index') }}"
      class="inline-block px-5 py-3 mt-6 text-sm font-medium text-white bg-blue-700 rounded hover:bg-indigo-800 focus:outline-none focus:ring">
      Regresar al inicio
    </a>
  </div>
</div>
{% endblock content %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tecnologías Web I</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/icon.png') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
    <script src="{{ url_for('static', filename='js/flowbite.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/main.js')}}" defer></script>
  </head>

  <body class="bg-white text-black dark:bg-gray-900 dark:text-white">
    <nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href= "{{ url_for('public.index') }}" class="flex items-center space-x-3 rtl:space-x-reverse">
          <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">CRUD citas</span>
        </a>
        <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
          <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
            <span class="sr-only">Menú</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
            </svg>
          </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
          <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
              <a href= "{{ url_for('public.index') }}" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Inicio</a>
            </li>
            {% if 'email' in session %}
            <li>
              <a href= "{{ url_for('private.citas') }}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Citas</a>
            </li>
            {% endif %}
            <li>
              <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Acerca de</a>
            </li>
            {% if not 'email' in session %}
              <a type="button" href="/auth/" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Ingresar</a>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} 
    {% endblock content %}

    <footer class="bg-white rounded-lg shadow m-4 dark:bg-gray-800">
      <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
        <span class="text-sm text-gray-500 dark:text-gray-300 sm:text-center">
          ©2024 Tecnologías Web I - Derechos Reservados.
        </span>
      </div>
    </footer>
  </body>
</html>